const RECEIVE_PHOTOSETS = 'RECEIVE_PHOTOSETS';
const RECIEVE_PHOTOSET = 'RECIEVE_PHOTOSET';
const RECEIVE_SIZES = 'RECEIVE_SIZES';

export default {
    RECEIVE_PHOTOSETS,
    RECIEVE_PHOTOSET,
    RECEIVE_SIZES,
};